id: P010390
initial_creation_type: ocr
source_metadata:
  id: bdr:W5JW16
  title: ཨཱལྟེས་གཡམནསིཨུམ་ཟུ་བྲེམེན
  author: ''
  volumes:
    49ee875ec44d44069c7407f4f45b135e:
      image_group_id: I1KG15577
      title: ''
      volume_number: 1
      total_pages: 43
